dist: xenial
sudo: false
language: python
cache: pip
python:
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - python -m pip install -U pip
  - python -m pip install -e .
  - python -m pip install flake8 pytest
  - python -m pip install keras
  - python -m pip install scikit-learn
# command to run tests
script:
  - pytest vae_oversampler
  - flake8 vae_oversampler